/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Metaphone.h
 #	source generated by 4D Plugin Wizard
 #	Project : Metaphone
 #	author : miyako
 #	2022/03/14
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_METAPHONE_H
#define PLUGIN_METAPHONE_H

#include "4DPluginAPI.h"

#include <vector>
#include <string>

#include <stdio.h>
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <assert.h>

#pragma mark -

static void DoubleMetaphone(PA_PluginParameters params);

#endif /* PLUGIN_METAPHONE_H */
